### ISSUE TITLE
Problemas (Cross Origin)

### ISSUE THREAD

**Issue by radiohunter** [vagalume/aplicativo-para-radios#9]
Olá pessoal, tudo bem?

Estou com um problema, mesmo colocando o ID da rádio tudo correto no aplicativo, ele não consegue reconhecer e fica em "branco". Em um teste pelo navegador usando o servidor do ionic e abrindo o inspecionador de elementos, notei que o servidor do Vagalume está bloqueando o acesso ao Json, dando um erro de Cross-Origin, ou seja, não consigo acessar o arquivo json pelo meu local e o app não sonegue obter as informações da estação (streams, nowplaying, capas e outros).

Poderiam me ajudar nisto?

Obrigado.

**Comment by lafraia** [comment]
@radiohunter Atualizamos o código no pull request #10. A URL estava incorreta e, com isso, não detectava o CORS corretamente. Pode atualizar e ver se resolve? Qualquer coisa pode reabrir este ticket.

Obrigado

**Comment by lafraia** [comment]
@radiohunter É possível que demore cerca de 24h até que todos os caches expirem. Desculpe.

**Comment by radiohunter** [comment]
A nova url fica assim? http://www.vagalume.com.br/json/radio/radio-hunter.json | A Url já está online com as informações da rádio.

Aqui no console não exibe mais o erro de cross-orign mas continua sem identificar a rádio, o ID está tudo correto. Console: http://prntscr.com/achiwk

**Comment by radiohunter** [comment]
A nova url fica assim? http://www.vagalume.com.br/json/radio/radio-hunter.json | A Url já está online com as informações da rádio.

Aqui no console não exibe mais o erro de cross-orign mas continua sem identificar a rádio, o ID está tudo correto. Console: http://prntscr.com/achiwk e http://prntscr.com/acvkbf

O app fica assim: http://prntscr.com/achjxc

**Comment by lafraia** [comment]
@radiohunter O ideal é usar a URL com o ID da rádio para que seja feito o correto redirecionamento para a URL completa. Se, por algum motivo, alterar o nome da rádio não precisaria mudar o app.

Baixando este projeto, bastaria colocar o ID da rádio no `www/manifest.json` nada mais (a não ser pela tela de splash).

Se não funcionar, por favor, indique o repositório no Github para a gente dar uma olhada ;-)
